# Generated by Django 4.0.4 on 2022-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_view',
        ),
        migrations.AddField(
            model_name='post',
            name='descript',
            field=models.TextField(default='description'),
        ),
    ]
