# Generated by Django 4.0.4 on 2022-05-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_blog_view_post_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='HTML form Attribute', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
