# Generated by Django 4.0.4 on 2022-05-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220524_1625'),
    ]

    operations = [
    ]
