# Generated by Django 4.0.4 on 2022-05-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220524_1626'),
    ]

    operations = [
    ]
